

# Define the root logger with appender file
log4j.rootLogger = all, FILE

# Define the file appender
log4j.appender.FILE=org.apache.log4j.FileAppender

# Set the name of the file
log4j.appender.FILE.File=${app.root}log.out

# Set the immediate flush to true (default)
log4j.appender.FILE.ImmediateFlush=true

# Set the threshold to debug mode
log4j.appender.FILE.Threshold=all

# Set the append to false, overwrite
log4j.appender.FILE.Append=false

#log4j.appender.FILE.MaxFileSize=10000000

# Define the layout for file appender
log4j.appender.FILE.layout=org.apache.log4j.PatternLayout
log4j.appender.FILE.layout.conversionPattern=[%-5p] %d{ISO8601}%c - %m%n



#status = error
#dest = err
#name = log4j.properties

#turns on debug app
#log4j.debug=true

#reset configuration
#log4j.reset=true

#set threshold
#log4j.threshold=all

#log4j.rootLogger

#log4j.rootCategory

#log4j.property.filename = ${app.root}/TPCdl.log
#log4j.property.filename = /home/white/OneDrive/Documents/TPCdl.log

#log4j.filter.threshold.type = ThresholdFilter
#log4j.filter.threshold.level = debug

#log4j.appender.console = org.apache.log4j.ConsoleAppender
#log4j.appender.console.layout = org.apache.log4j.PatternLayout
#log4j.appender.console.layout.pattern = %m%n or %m MDC%X%n or %d %p %C{1.} [%t] %m%n
#class name and line number
#log4j.appender.console.layout.ConversionPattern = %C{1}.%M %m %ex%n
#log4j.appender.console.filter.threshold.type = thresholdFilter
#log4j.appender.console.filter.threshold.level = error

#log4j.appender.rolling = org.apache.log4j.RollingFileAppender
#log4j.appender.rolling.file = ${filename}
#log4j.appender.rolling.layout = org.apache.log4j.PatternLayout
#log4j.appender.rolling.layout.ConversionPattern = %d %p %C{1} [%t] %m%n
#log4j.appender.rolling.MaxFileSize = 300KB
#log4j.appender.rolling.append = false

#log4j.logger.rolling.level = debug

#log4j.rootLogger.level = info


# Set root logger level to DEBUG and its appender(s)
#log4j.rootLogger=DEBUG, rolling

# A1 is set to be a ConsoleAppender.
#log4j.log4j.appender.A1=org.apache.log4j.ConsoleAppender

# A1 uses PatternLayout.
#log4j.log4j.appender.A1.layout=org.apache.log4j.PatternLayout
#log4j.log4j.appender.A1.layout.ConversionPattern=%-4r [%t] %-5p %c %x - %m%n

# Print only messages of level WARN or above in the package com.foo.
#log4j.logger.com.foo=WARN